[package]
name = "parser"
version = "0.0.0"
edition = "2021"

[dependencies]
lexer.workspace = true
# lalrpop-util = { workspace = true , features = ["lexer", "unicode"] } 
anyhow.workspace = true


[build-dependencies]
# lalrpop.workspace = true
